# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp20058_gibbsC', PACKAGE = 'StatComp20058', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param age the first predictor (numeric)
#' @param female the second predictor (logical)
#' @param ily the third predictor (logical)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' res <- vaccC(age,female,ily)
#' }
#' @export
vaccC <- function(age, female, ily) {
    .Call('_StatComp20058_vaccC', PACKAGE = 'StatComp20058', age, female, ily)
}

#' @title A  Metropolis samplered using Rcpp
#' @description A Metropolis samplered using Rcpp
#' @param sigma the sigma of samples
#' @param x0   a parameter
#' @param N   sample of size
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' x0<-25
#' sigma<-c(0.05,1,2,16)
#' N<-3000
#' M1=MetropolisC(sigma[1],x0,N)
#' M2=MetropolisC(sigma[2],x0,N)
#' M3=MetropolisC(sigma[3],x0,N)
#' M4=MetropolisC(sigma[4],x0,N)
#' acceptanceC<-1-c(M1[[2]][1],M2[[2]][1],M3[[2]][1],M4[[2]][1])/N
#' index<-1:2000
#' My1<-M1[[1]][index]
#' My2<-M2[[1]][index]
#' My3<-M3[[1]][index]
#' My4<-M4[[1]][index]
#' opar<-par(no.readonly = T)
#' par(mfrow=c(2,2))
#' plot(index,My1,type = "l",xlab = "sigma=0.05")
#' plot(index,My2,type = "l",xlab = "sigma=1")
#' plot(index,My3,type = "l",xlab = "sigma=2")
#' plot(index,My4,type = "l",xlab = "sigam=16")
#' }
#' @export
MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20058_MetropolisC', PACKAGE = 'StatComp20058', sigma, x0, N)
}

