// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gibbsC
NumericMatrix gibbsC(int N, int thin);
RcppExport SEXP _StatComp20058_gibbsC(SEXP NSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsC(N, thin));
    return rcpp_result_gen;
END_RCPP
}
// vaccC
NumericVector vaccC(NumericVector age, LogicalVector female, LogicalVector ily);
RcppExport SEXP _StatComp20058_vaccC(SEXP ageSEXP, SEXP femaleSEXP, SEXP ilySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type age(ageSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type female(femaleSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type ily(ilySEXP);
    rcpp_result_gen = Rcpp::wrap(vaccC(age, female, ily));
    return rcpp_result_gen;
END_RCPP
}
// MetropolisC
List MetropolisC(double sigma, double x0, int N);
RcppExport SEXP _StatComp20058_MetropolisC(SEXP sigmaSEXP, SEXP x0SEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(MetropolisC(sigma, x0, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp20058_gibbsC", (DL_FUNC) &_StatComp20058_gibbsC, 2},
    {"_StatComp20058_vaccC", (DL_FUNC) &_StatComp20058_vaccC, 3},
    {"_StatComp20058_MetropolisC", (DL_FUNC) &_StatComp20058_MetropolisC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp20058(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
